version: 2

updates:
  - package-ecosystem: github-actions
    directory: ".github/workflows"
    target-branch: "main"

    schedule:
      interval: daily
      timezone: "Europe/Paris"
      time: "00:00"

    labels:
      - "source:ğŸ’š github_actions"
      - "source:ğŸ¤– bot"

    commit-message:
      prefix: "â¬†ï¸ upgrade(ci)"
